/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/weather/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest */
        get: operations["latest_weather"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/aqi/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest */
        get: operations["latest_aqi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/flood/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest */
        get: operations["latest_flood"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/heat/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest */
        get: operations["latest_heat"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recommend/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest */
        get: operations["latest_recommend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/simulation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate
         * @description Live what-if against the latest weather/flood/aqi snapshots (what legacy runSimulation fetched).
         */
        post: operations["simulate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/history/{hazard}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History
         * @description Snapshots of the last `hours`, oldest first.
         */
        get: operations["history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AQIForecastItem */
        AQIForecastItem: {
            /** Hour */
            hour: string;
            /** Aqi */
            aqi: number;
        } & {
            [key: string]: unknown;
        };
        /** AQILatest */
        AQILatest: {
            /**
             * Observedat
             * @description computed_at of the snapshot, ISO 8601 UTC
             */
            observedAt: string;
            /**
             * Stale
             * @description true when the snapshot is older than STALE_AFTER_MINUTES
             */
            stale: boolean;
            /** Aqi */
            aqi: number;
            /** Category */
            category: string;
            /** Pm25 */
            pm25: number;
            /** Pm10 */
            pm10: number;
            /** O3 */
            o3: number;
            /** No2 */
            no2: number;
            /**
             * Trend
             * @enum {string}
             */
            trend: "increasing" | "decreasing" | "stable";
            /** Forecast24H */
            forecast24h: components["schemas"]["AQIForecastItem"][];
            /** Stations */
            stations: components["schemas"]["AQIStation"][];
        } & {
            [key: string]: unknown;
        };
        /** AQIStation */
        AQIStation: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Aqi */
            aqi: number;
        } & {
            [key: string]: unknown;
        };
        /** Alert */
        Alert: {
            /** Id */
            id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "critical";
            /**
             * Type
             * @enum {string}
             */
            type: "flood" | "aqi" | "heat" | "storm" | "system";
            /** Title */
            title: string;
            /** Message */
            message: string;
            /** Isread */
            isRead: boolean;
            /** Createdat */
            createdAt: string;
            /** Expiresat */
            expiresAt: string;
        };
        /** AlertsResponse */
        AlertsResponse: {
            /** Alerts */
            alerts: components["schemas"]["Alert"][];
            /** Unreadcount */
            unreadCount: number;
            /** Totalcount */
            totalCount: number;
        };
        /** FloodArea */
        FloodArea: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /**
             * Risklevel
             * @enum {string}
             */
            riskLevel: "low" | "medium" | "high" | "critical";
            /** Riskscore */
            riskScore: number;
            /** Estimateddepth */
            estimatedDepth: number;
            geojson: components["schemas"]["FloodGeoJSONFeature"];
        } & {
            [key: string]: unknown;
        };
        /** FloodGeoJSONFeature */
        FloodGeoJSONFeature: {
            /**
             * Type
             * @constant
             */
            type: "Feature";
            geometry: components["schemas"]["PolygonGeometry"];
            /** Properties */
            properties: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** FloodLatest */
        FloodLatest: {
            /**
             * Observedat
             * @description computed_at of the snapshot, ISO 8601 UTC
             */
            observedAt: string;
            /**
             * Stale
             * @description true when the snapshot is older than STALE_AFTER_MINUTES
             */
            stale: boolean;
            /** Overallrisk */
            overallRisk: string;
            /** Riskscore */
            riskScore: number;
            /** Affectedareas */
            affectedAreas: components["schemas"]["FloodArea"][];
            triggers: components["schemas"]["FloodTriggers"];
        } & {
            [key: string]: unknown;
        };
        /** FloodTriggers */
        FloodTriggers: {
            /** Currentrainfall */
            currentRainfall: number;
            /** Soilsaturation */
            soilSaturation: number;
            /** Drainagecapacity */
            drainageCapacity: number;
            /** Terrainsensitivity */
            terrainSensitivity: number;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeatFeature */
        HeatFeature: {
            /**
             * Type
             * @constant
             */
            type: "Feature";
            geometry: components["schemas"]["PointGeometry"];
            properties: components["schemas"]["HeatFeatureProps"];
        } & {
            [key: string]: unknown;
        };
        /** HeatFeatureProps */
        HeatFeatureProps: {
            /** Temperature */
            temperature: number;
            /** Intensity */
            intensity: number;
        } & {
            [key: string]: unknown;
        };
        /** HeatGeoJSON */
        HeatGeoJSON: {
            /**
             * Type
             * @constant
             */
            type: "FeatureCollection";
            /** Features */
            features: components["schemas"]["HeatFeature"][];
        } & {
            [key: string]: unknown;
        };
        /** HeatHotspot */
        HeatHotspot: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Temperature */
            temperature: number;
            /** Intensity */
            intensity: number;
        } & {
            [key: string]: unknown;
        };
        /** HeatLatest */
        HeatLatest: {
            /**
             * Observedat
             * @description computed_at of the snapshot, ISO 8601 UTC
             */
            observedAt: string;
            /**
             * Stale
             * @description true when the snapshot is older than STALE_AFTER_MINUTES
             */
            stale: boolean;
            /** City */
            city: string;
            /** Timestamp */
            timestamp: string;
            /** Avgtemperature */
            avgTemperature: number;
            /** Maxtemperature */
            maxTemperature: number;
            /** Heatislandintensity */
            heatIslandIntensity: number;
            /** Avgeffectivetemperature */
            avgEffectiveTemperature?: number | null;
            /** Hotspots */
            hotspots: components["schemas"]["HeatHotspot"][];
            geojson: components["schemas"]["HeatGeoJSON"];
        } & {
            [key: string]: unknown;
        };
        /** HistoryEntry */
        HistoryEntry: {
            /** Computedat */
            computedAt: string;
            /**
             * Result
             * @description that hazard's /latest shape as it was at computedAt
             */
            result: {
                [key: string]: unknown;
            };
        };
        /** MarkReadRequest */
        MarkReadRequest: {
            /** Ids */
            ids: string[];
        };
        /** MarkReadResponse */
        MarkReadResponse: {
            /**
             * Marked
             * @description how many of the ids were unread and are now read
             */
            marked: number;
        };
        /** PointGeometry */
        PointGeometry: {
            /** Type */
            type: string;
            /** Coordinates */
            coordinates: number[];
        } & {
            [key: string]: unknown;
        };
        /** PolygonGeometry */
        PolygonGeometry: {
            /** Type */
            type: string;
            /** Coordinates */
            coordinates: number[][][];
        } & {
            [key: string]: unknown;
        };
        /** RecommendLatest */
        RecommendLatest: {
            /**
             * Observedat
             * @description computed_at of the snapshot, ISO 8601 UTC
             */
            observedAt: string;
            /**
             * Stale
             * @description true when the snapshot is older than STALE_AFTER_MINUTES
             */
            stale: boolean;
            /** Recommendations */
            recommendations: components["schemas"]["Recommendation"][];
            /** Summary */
            summary: string;
            /**
             * Overallrisklevel
             * @enum {string}
             */
            overallRiskLevel: "low" | "medium" | "high" | "critical";
        } & {
            [key: string]: unknown;
        };
        /** Recommendation */
        Recommendation: {
            /** Id */
            id: string;
            /** Ruleid */
            ruleId: string;
            /** Priorityscore */
            priorityScore: number;
            /**
             * Priority
             * @enum {string}
             */
            priority: "low" | "medium" | "high" | "urgent";
            /**
             * Category
             * @enum {string}
             */
            category: "flood" | "air" | "heat" | "combined";
            /** Title */
            title: string;
            /** Message */
            message: string;
            /** Actionitems */
            actionItems: string[];
            /** Timestamp */
            timestamp: string;
            /** Inputs */
            inputs: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /**
         * Scenario
         * @description Bounds = legacy validateScenario. Omitted/null levers take the legacy controller defaults.
         */
        Scenario: {
            /**
             * Rainfallincrease
             * @default 50
             */
            rainfallIncrease?: number;
            /**
             * Rainfalldurationhours
             * @default 3
             */
            rainfallDurationHours?: number;
            /**
             * Addgreencoverage
             * @description percentage points vs baseline
             * @default 0
             */
            addGreenCoverage?: number;
            /**
             * Trafficreduction
             * @default 0
             */
            trafficReduction?: number;
            /**
             * Urbandensity
             * @description omitted = baseline density
             */
            urbanDensity?: number | null;
        };
        /** SimComparison */
        SimComparison: {
            before: components["schemas"]["SimComparisonSide"];
            after: components["schemas"]["SimComparisonSide"];
        };
        /** SimComparisonSide */
        SimComparisonSide: {
            /** Riskscore */
            riskScore: number;
            /** Affectedareas */
            affectedAreas: number;
        };
        /** SimResults */
        SimResults: {
            /** Floodriskdelta */
            floodRiskDelta: number;
            /** Newfloodareas */
            newFloodAreas: components["schemas"]["FloodArea"][];
            /** Tempdelta */
            tempDelta: number;
            /** Aqidelta */
            aqiDelta: number;
            /** Affectedbuildings */
            affectedBuildings: number;
            /** Affectedpopulation */
            affectedPopulation: number;
        };
        /** SimulationRequest */
        SimulationRequest: {
            /**
             * Cityid
             * @default hcmc
             */
            cityId?: string;
            scenario?: components["schemas"]["Scenario"];
        };
        /** SimulationResult */
        SimulationResult: {
            /** Simulationid */
            simulationId: string;
            /** Status */
            status: string;
            results: components["schemas"]["SimResults"];
            comparison: components["schemas"]["SimComparison"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeatherCurrent */
        WeatherCurrent: {
            /** Temperature */
            temperature: number;
            /** Feelslike */
            feelsLike: number;
            /** Humidity */
            humidity: number;
            /** Rainfall */
            rainfall: number;
            /** Windspeed */
            windSpeed: number;
            /** Winddirection */
            windDirection: number;
            /** Condition */
            condition: string;
            /** Timestamp */
            timestamp: string;
        } & {
            [key: string]: unknown;
        };
        /** WeatherForecastItem */
        WeatherForecastItem: {
            /** Hour */
            hour: string;
            /** Temperature */
            temperature: number;
            /** Rainfall */
            rainfall: number;
            /** Windspeed */
            windSpeed: number;
            /** Stormprobability */
            stormProbability: number;
        } & {
            [key: string]: unknown;
        };
        /** WeatherLatest */
        WeatherLatest: {
            /**
             * Observedat
             * @description computed_at of the snapshot, ISO 8601 UTC
             */
            observedAt: string;
            /**
             * Stale
             * @description true when the snapshot is older than STALE_AFTER_MINUTES
             */
            stale: boolean;
            current: components["schemas"]["WeatherCurrent"];
            /** Forecast */
            forecast: components["schemas"]["WeatherForecastItem"][];
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    latest_weather: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherLatest"];
                };
            };
            /** @description no snapshot yet */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    latest_aqi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AQILatest"];
                };
            };
            /** @description no snapshot yet */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    latest_flood: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FloodLatest"];
                };
            };
            /** @description no snapshot yet */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    latest_heat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeatLatest"];
                };
            };
            /** @description no snapshot yet */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    latest_recommend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendLatest"];
                };
            };
            /** @description no snapshot yet */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_alerts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertsResponse"];
                };
            };
        };
    };
    mark_read: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkReadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description no snapshot yet */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    history: {
        parameters: {
            query?: {
                hours?: number;
            };
            header?: never;
            path: {
                hazard: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
