/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/weather/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest */
        get: operations["latest_weather"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/aqi/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest */
        get: operations["latest_aqi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/flood/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest */
        get: operations["latest_flood"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/heat/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest */
        get: operations["latest_heat"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recommend/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest */
        get: operations["latest_recommend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alerts
         * @description Active per-unit alerts (§F), newest first, critical before warning within a run. Rows of the
         *     pre-S-002 types (the dropped always-on `system` / `info` alert) are not served.
         */
        get: operations["list_alerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/simulation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate
         * @description What-if (§G, Algorithm 2 step 7): scoring, alerts and ℛ re-run on the counterfactual state
         *     built from the latest flood, heat and aqi snapshots.
         */
        post: operations["simulate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/maturity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Maturity
         * @description Algorithm 1 evaluated now on the stored history (§H line 8).
         */
        get: operations["maturity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Units
         * @description Unit -> 2025 commune mapping table of the data layer (§A.3), from the committed catalogue.
         */
        get: operations["units"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/history/{hazard}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History
         * @description Snapshots of the last `hours`, oldest first.
         */
        get: operations["history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AQIForecastItem */
        AQIForecastItem: {
            /** Hour */
            hour: string;
            /** Aqi */
            aqi: number;
        } & {
            [key: string]: unknown;
        };
        /** AQILatest */
        AQILatest: {
            /**
             * Observedat
             * @description computed_at of the snapshot, ISO 8601 UTC
             */
            observedAt: string;
            /**
             * Stale
             * @description true when the snapshot is older than STALE_AFTER_MINUTES
             */
            stale: boolean;
            /**
             * Modelversion
             * @description model of the snapshot: pdim-s1, or pdim-s2-aqi for aqi while S2 is active (§H)
             */
            modelVersion: string;
            /** Aqi */
            aqi: number;
            /** Category */
            category: string;
            /** Pm25 */
            pm25: number;
            /** Pm10 */
            pm10: number;
            /** O3 */
            o3: number;
            /** No2 */
            no2: number;
            /**
             * Trend
             * @enum {string}
             */
            trend: "increasing" | "decreasing" | "stable";
            /**
             * Forecast24H
             * @description uses the fitted γ while S2 is active (§H)
             */
            forecast24h: components["schemas"]["AQIForecastItem"][];
            /** Stations */
            stations: components["schemas"]["AQIStation"][];
            /** Observedstations */
            observedStations: components["schemas"]["ObservedStation"][];
        } & {
            [key: string]: unknown;
        };
        /** AQIStation */
        AQIStation: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Aqi */
            aqi: number;
        } & {
            [key: string]: unknown;
        };
        /** Alert */
        Alert: {
            /**
             * Id
             * @description <hazard>:<unitId>:<warning|critical>:<YYYY-MM-DDTHH local>
             */
            id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "warning" | "critical";
            /**
             * Type
             * @enum {string}
             */
            type: "flood" | "storm" | "aqi" | "heat";
            /** Title */
            title: string;
            /** Message */
            message: string;
            /** Unitid */
            unitId?: string | null;
            /** Unitname */
            unitName?: string | null;
            /** Value */
            value?: number | null;
            /** Isread */
            isRead: boolean;
            /** Createdat */
            createdAt: string;
            /** Expiresat */
            expiresAt: string;
        };
        /** AlertsResponse */
        AlertsResponse: {
            /** Alerts */
            alerts: components["schemas"]["Alert"][];
            /** Unreadcount */
            unreadCount: number;
            /** Totalcount */
            totalCount: number;
        };
        /** BandChange */
        BandChange: {
            /** Unitid */
            unitId: string;
            /** Name */
            name: string;
            /** Before */
            before: string;
            /** After */
            after: string;
        };
        /** BandChanges */
        BandChanges: {
            /**
             * Flood
             * @description bands low / medium / high / critical
             */
            flood: components["schemas"]["BandChange"][];
            /**
             * Heat
             * @description bands low / moderate / high / extreme
             */
            heat: components["schemas"]["BandChange"][];
            /**
             * Aqi
             * @description AQI level codes good … hazardous
             */
            aqi: components["schemas"]["BandChange"][];
        };
        /**
         * Counterfactual
         * @description Algorithm 2 steps 3–6 re-run on the counterfactual state (§G).
         */
        Counterfactual: {
            /**
             * Recommendations
             * @description top k, same shape as /v1/recommend
             */
            recommendations: components["schemas"]["Recommendation"][];
            /** Firedcount */
            firedCount: number;
            /** Alerts */
            alerts: components["schemas"]["SimAlert"][];
            bandChanges: components["schemas"]["BandChanges"];
        };
        /** Criterion */
        Criterion: {
            /** Name */
            name: string;
            /** Current */
            current: number;
            /** Required */
            required: number;
        };
        /** FloodArea */
        FloodArea: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /**
             * Risklevel
             * @enum {string}
             */
            riskLevel: "low" | "medium" | "high" | "critical";
            /** Riskscore */
            riskScore: number;
            /** Estimateddepth */
            estimatedDepth: number;
            /**
             * Rainfall
             * @description P(i), mm/h at the zone's own coordinate
             */
            rainfall: number;
            /**
             * Decomposition
             * @description Σ contribution = R_f(i) before the clamp
             */
            decomposition: components["schemas"]["FloodTerm"][];
            geojson: components["schemas"]["FloodGeoJSONFeature"];
        } & {
            [key: string]: unknown;
        };
        /** FloodGeoJSONFeature */
        FloodGeoJSONFeature: {
            /**
             * Type
             * @constant
             */
            type: "Feature";
            geometry: components["schemas"]["PolygonGeometry"];
            /** Properties */
            properties: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** FloodLatest */
        FloodLatest: {
            /**
             * Observedat
             * @description computed_at of the snapshot, ISO 8601 UTC
             */
            observedAt: string;
            /**
             * Stale
             * @description true when the snapshot is older than STALE_AFTER_MINUTES
             */
            stale: boolean;
            /**
             * Modelversion
             * @description model of the snapshot: pdim-s1, or pdim-s2-aqi for aqi while S2 is active (§H)
             */
            modelVersion: string;
            /** Overallrisk */
            overallRisk: string;
            /** Riskscore */
            riskScore: number;
            /** Affectedareas */
            affectedAreas: components["schemas"]["FloodArea"][];
            triggers: components["schemas"]["FloodTriggers"];
            /**
             * Decomposition
             * @description city level; Σ contribution = R_f before the clamp
             */
            decomposition: components["schemas"]["FloodTerm"][];
        } & {
            [key: string]: unknown;
        };
        /**
         * FloodTerm
         * @description One R_f term ready to render (§B, B-014): the web holds no PDIM weight.
         */
        FloodTerm: {
            /**
             * Key
             * @enum {string}
             */
            key: "rainfall" | "terrain" | "imperviousness" | "drainage";
            /**
             * Weight
             * @description w_i > 0
             */
            weight: number;
            /**
             * Normalized
             * @description x̃_i in [0, 1]
             */
            normalized: number;
            /**
             * Contribution
             * @description w_i·x̃_i; negative for drainage
             */
            contribution: number;
        } & {
            [key: string]: unknown;
        };
        /** FloodTriggers */
        FloodTriggers: {
            /**
             * Currentrainfall
             * @description city-centre P, mm/h
             */
            currentRainfall: number;
            /**
             * Terrainsensitivity
             * @description mean T̃ over the 18 zones
             */
            terrainSensitivity: number;
            /**
             * Imperviousness
             * @description mean Ĩ over the 18 zones
             */
            imperviousness: number;
            /**
             * Drainagecapacity
             * @description mean D̃ over the 18 zones
             */
            drainageCapacity: number;
        } & {
            [key: string]: unknown;
        };
        /** GammaEstimate */
        GammaEstimate: {
            /**
             * Value
             * @description estimate clamped to [0, 1]
             */
            value: number;
            /**
             * Estimate
             * @description OLS estimate, unclamped
             */
            estimate: number;
            /** Se */
            se: number;
            /**
             * Ci95
             * @description [lo, hi] around the unclamped estimate
             */
            ci95: number[];
        };
        /** GammaEstimates */
        GammaEstimates: {
            gammaWind: components["schemas"]["GammaEstimate"];
            gammaRain: components["schemas"]["GammaEstimate"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HazardMaturity */
        HazardMaturity: {
            /**
             * Hazard
             * @enum {string}
             */
            hazard: "flood" | "heat" | "aqi";
            /**
             * Active
             * @enum {string}
             */
            active: "S1" | "S2" | "S3";
            /** Modelversion */
            modelVersion: string;
            stages: components["schemas"]["Stages"];
            /**
             * S1Maeholdout
             * @description S1 one-step holdout MAE where V exists
             */
            s1MaeHoldout: number | null;
            /** @description S2 fit when eligible and fitted */
            s2: components["schemas"]["S2Fit"] | null;
        };
        /**
         * HeatBaselines
         * @description What-if reference state (§C); the heat sliders start here.
         */
        HeatBaselines: {
            /**
             * Density
             * @description ρ₀ = mean builtUp over the 22 cells, 0–1
             */
            density: number;
            /**
             * Greenpct
             * @description G₀ = mean green cover over the 22 cells, %
             */
            greenPct: number;
        } & {
            [key: string]: unknown;
        };
        /** HeatFeature */
        HeatFeature: {
            /**
             * Type
             * @constant
             */
            type: "Feature";
            geometry: components["schemas"]["PointGeometry"];
            properties: components["schemas"]["HeatFeatureProps"];
        } & {
            [key: string]: unknown;
        };
        /** HeatFeatureProps */
        HeatFeatureProps: {
            /** Temperature */
            temperature: number;
            /** Intensity */
            intensity: number;
        } & {
            [key: string]: unknown;
        };
        /** HeatGeoJSON */
        HeatGeoJSON: {
            /**
             * Type
             * @constant
             */
            type: "FeatureCollection";
            /** Features */
            features: components["schemas"]["HeatFeature"][];
        } & {
            [key: string]: unknown;
        };
        /** HeatHotspot */
        HeatHotspot: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Temperature */
            temperature: number;
            /** Intensity */
            intensity: number;
        } & {
            [key: string]: unknown;
        };
        /** HeatLatest */
        HeatLatest: {
            /**
             * Observedat
             * @description computed_at of the snapshot, ISO 8601 UTC
             */
            observedAt: string;
            /**
             * Stale
             * @description true when the snapshot is older than STALE_AFTER_MINUTES
             */
            stale: boolean;
            /**
             * Modelversion
             * @description model of the snapshot: pdim-s1, or pdim-s2-aqi for aqi while S2 is active (§H)
             */
            modelVersion: string;
            /** City */
            city: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Avgtemperature
             * @description city-centre AIR temperature, °C
             */
            avgTemperature: number;
            /**
             * Maxtemperature
             * @description max T_eff(i), °C
             */
            maxTemperature: number;
            /** Heatislandintensity */
            heatIslandIntensity: number;
            /**
             * Avgeffectivetemperature
             * @description mean T_eff(i), the heat what-if baseline (B-020)
             */
            avgEffectiveTemperature: number;
            baselines: components["schemas"]["HeatBaselines"];
            /** Hotspots */
            hotspots: components["schemas"]["HeatHotspot"][];
            geojson: components["schemas"]["HeatGeoJSON"];
        } & {
            [key: string]: unknown;
        };
        /** HistoryEntry */
        HistoryEntry: {
            /** Computedat */
            computedAt: string;
            /**
             * Result
             * @description that hazard's /latest shape as it was at computedAt
             */
            result: {
                [key: string]: unknown;
            };
        };
        /** MarkReadRequest */
        MarkReadRequest: {
            /** Ids */
            ids: string[];
        };
        /** MarkReadResponse */
        MarkReadResponse: {
            /**
             * Marked
             * @description how many of the ids were unread and are now read
             */
            marked: number;
        };
        /** MaturityResponse */
        MaturityResponse: {
            /** Evaluatedat */
            evaluatedAt: string;
            /** Windowdays */
            windowDays: number;
            /** Deltaaqi */
            deltaAqi: number;
            /** Hazards */
            hazards: components["schemas"]["HazardMaturity"][];
        };
        /**
         * ObservedStation
         * @description Open monitoring network station (§I.3), served apart from the CAMS points; feeds §H.
         */
        ObservedStation: {
            /**
             * Id
             * @description ag:<locationId>
             */
            id: string;
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /**
             * Aqi
             * @description US AQI from the station's PM2.5
             */
            aqi: number;
            /**
             * Pm25
             * @description µg/m³
             */
            pm25: number;
            /** Observedat */
            observedAt: string;
            /** Source */
            source: string;
            /**
             * Nearestpointid
             * @description nearest AQI point (§A.4)
             */
            nearestPointId: string;
        } & {
            [key: string]: unknown;
        };
        /** PointGeometry */
        PointGeometry: {
            /** Type */
            type: string;
            /** Coordinates */
            coordinates: number[];
        } & {
            [key: string]: unknown;
        };
        /** PolygonGeometry */
        PolygonGeometry: {
            /** Type */
            type: string;
            /** Coordinates */
            coordinates: number[][][];
        } & {
            [key: string]: unknown;
        };
        /** RecommendLatest */
        RecommendLatest: {
            /**
             * Observedat
             * @description computed_at of the snapshot, ISO 8601 UTC
             */
            observedAt: string;
            /**
             * Stale
             * @description true when the snapshot is older than STALE_AFTER_MINUTES
             */
            stale: boolean;
            /**
             * Modelversion
             * @description model of the snapshot: pdim-s1, or pdim-s2-aqi for aqi while S2 is active (§H)
             */
            modelVersion: string;
            /**
             * Recommendations
             * @description top k = 10 by π desc
             */
            recommendations: components["schemas"]["Recommendation"][];
            /**
             * Firedcount
             * @description all fired (r, i), before the top-k cut
             */
            firedCount: number;
            /** Summary */
            summary: string;
            /**
             * Overallrisklevel
             * @enum {string}
             */
            overallRiskLevel: "low" | "medium" | "high" | "critical";
        } & {
            [key: string]: unknown;
        };
        /** Recommendation */
        Recommendation: {
            /**
             * Id
             * @description <ruleId>:<unitId>
             */
            id: string;
            /** Ruleid */
            ruleId: string;
            /** Unitid */
            unitId: string;
            /**
             * Unitname
             * @description toponym
             */
            unitName: string;
            /**
             * Unitkind
             * @enum {string}
             */
            unitKind: "flood_zone" | "heat_cell" | "aqi_point" | "city";
            /**
             * Commune
             * @description official 2025 commune containing the unit (§A.3): data/API only, never rendered
             */
            commune: string | null;
            /**
             * Priorityscore
             * @description π(r, i) = S(b)·E(i)·F(a)
             */
            priorityScore: number;
            /**
             * Priority
             * @enum {string}
             */
            priority: "low" | "medium" | "high" | "urgent";
            /**
             * Category
             * @enum {string}
             */
            category: "flood" | "air" | "heat" | "combined";
            /** Title */
            title: string;
            /** Message */
            message: string;
            /** Actionitems */
            actionItems: string[];
            /** Timestamp */
            timestamp: string;
            inputs: components["schemas"]["RecommendationInputs"];
        } & {
            [key: string]: unknown;
        };
        /**
         * RecommendationInputs
         * @description The unit's value(s) the rule fired on (flood: riskScore, rainfall; R-COMB-01: riskScore, aqi,
         *     aqiPointId; AQI: aqi; heat: effectiveTemperature) + the π(r, i) factors. R-NORM-00 carries only
         *     severityBand "none".
         */
        RecommendationInputs: {
            /** Severityband */
            severityBand: string;
            /**
             * Exposuree
             * @description E(i) = clamp(builtUp(i), 0.1, 1)
             */
            exposureE?: number | null;
            /**
             * Feasibilityfa
             * @description F(a)
             */
            feasibilityFa?: number | null;
            /** Riskscore */
            riskScore?: number | null;
            /** Rainfall */
            rainfall?: number | null;
            /** Aqi */
            aqi?: number | null;
            /** Aqipointid */
            aqiPointId?: string | null;
            /** Effectivetemperature */
            effectiveTemperature?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** S2Fit */
        S2Fit: {
            estimates: components["schemas"]["GammaEstimates"];
            /** Maeholdout */
            maeHoldout: number | null;
            /** Ntrain */
            nTrain: number;
            /** Nholdout */
            nHoldout: number;
            /** Promoted */
            promoted: boolean;
        };
        /**
         * Scenario
         * @description Bounds = legacy validateScenario. Omitted/null levers take the legacy controller defaults.
         */
        Scenario: {
            /**
             * Rainfallincrease
             * @default 50
             */
            rainfallIncrease?: number;
            /**
             * Rainfalldurationhours
             * @default 3
             */
            rainfallDurationHours?: number;
            /**
             * Addgreencoverage
             * @description percentage points vs baseline
             * @default 0
             */
            addGreenCoverage?: number;
            /**
             * Trafficreduction
             * @default 0
             */
            trafficReduction?: number;
            /**
             * Urbandensity
             * @description omitted = baseline density
             */
            urbanDensity?: number | null;
        };
        /**
         * SimAlert
         * @description An alert that WOULD fire on the counterfactual state (returned, never persisted).
         */
        SimAlert: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "flood" | "storm" | "aqi" | "heat";
            /**
             * Severity
             * @enum {string}
             */
            severity: "warning" | "critical";
            /** Unitid */
            unitId: string;
            /** Unitname */
            unitName: string;
            /** Value */
            value: number;
            /** Title */
            title: string;
            /** Message */
            message: string;
            /** Createdat */
            createdAt: string;
            /** Expiresat */
            expiresAt: string;
        };
        /** SimComparison */
        SimComparison: {
            before: components["schemas"]["SimComparisonSide"];
            after: components["schemas"]["SimComparisonSide"];
        };
        /** SimComparisonSide */
        SimComparisonSide: {
            /** Riskscore */
            riskScore: number;
            /** Affectedareas */
            affectedAreas: number;
        };
        /** SimResults */
        SimResults: {
            /** Floodriskdelta */
            floodRiskDelta: number;
            /** Newfloodareas */
            newFloodAreas: components["schemas"]["FloodArea"][];
            /** Tempdelta */
            tempDelta: number;
            /** Aqidelta */
            aqiDelta: number;
            /**
             * Stations
             * @description per AQI point: AQI_sim(i) (§D)
             */
            stations: components["schemas"]["SimStation"][];
        };
        /** SimStation */
        SimStation: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Before */
            before: number;
            /** After */
            after: number;
            /** Delta */
            delta: number;
        };
        /** SimulationRequest */
        SimulationRequest: {
            /**
             * Cityid
             * @default hcmc
             */
            cityId?: string;
            scenario?: components["schemas"]["Scenario"];
        };
        /** SimulationResult */
        SimulationResult: {
            /** Simulationid */
            simulationId: string;
            /** Status */
            status: string;
            results: components["schemas"]["SimResults"];
            comparison: components["schemas"]["SimComparison"];
            counterfactual: components["schemas"]["Counterfactual"];
        };
        /** Stage */
        Stage: {
            /** Eligible */
            eligible: boolean;
            /** Reason */
            reason?: string | null;
            /** Criteria */
            criteria: components["schemas"]["Criterion"][];
        };
        /** Stages */
        Stages: {
            S1: components["schemas"]["Stage"];
            S2: components["schemas"]["Stage"];
            S3: components["schemas"]["Stage"];
        };
        /**
         * UnitRow
         * @description One spatial unit and its 2025 commune (spec §A.3 mapping table). Data/API only: the web
         *     never renders `commune`.
         */
        UnitRow: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "flood_zone" | "heat_cell" | "aqi_point";
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Commune */
            commune: string | null;
            /** Communeosmid */
            communeOsmId: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeatherCurrent */
        WeatherCurrent: {
            /** Temperature */
            temperature: number;
            /** Feelslike */
            feelsLike: number;
            /** Humidity */
            humidity: number;
            /** Rainfall */
            rainfall: number;
            /** Windspeed */
            windSpeed: number;
            /** Winddirection */
            windDirection: number;
            /** Condition */
            condition: string;
            /** Timestamp */
            timestamp: string;
        } & {
            [key: string]: unknown;
        };
        /** WeatherForecastItem */
        WeatherForecastItem: {
            /** Hour */
            hour: string;
            /** Temperature */
            temperature: number;
            /** Rainfall */
            rainfall: number;
            /** Windspeed */
            windSpeed: number;
            /** Stormprobability */
            stormProbability: number;
        } & {
            [key: string]: unknown;
        };
        /** WeatherLatest */
        WeatherLatest: {
            /**
             * Observedat
             * @description computed_at of the snapshot, ISO 8601 UTC
             */
            observedAt: string;
            /**
             * Stale
             * @description true when the snapshot is older than STALE_AFTER_MINUTES
             */
            stale: boolean;
            /**
             * Modelversion
             * @description model of the snapshot: pdim-s1, or pdim-s2-aqi for aqi while S2 is active (§H)
             */
            modelVersion: string;
            current: components["schemas"]["WeatherCurrent"];
            /** Forecast */
            forecast: components["schemas"]["WeatherForecastItem"][];
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    latest_weather: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherLatest"];
                };
            };
            /** @description no snapshot yet, or none in the current (S-002) shape */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    latest_aqi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AQILatest"];
                };
            };
            /** @description no snapshot yet, or none in the current (S-002) shape */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    latest_flood: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FloodLatest"];
                };
            };
            /** @description no snapshot yet, or none in the current (S-002) shape */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    latest_heat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeatLatest"];
                };
            };
            /** @description no snapshot yet, or none in the current (S-002) shape */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    latest_recommend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendLatest"];
                };
            };
            /** @description no snapshot yet, or none in the current (S-002) shape */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_alerts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertsResponse"];
                };
            };
        };
    };
    mark_read: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkReadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description no snapshot yet, or none in the current (S-002) shape */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    maturity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaturityResponse"];
                };
            };
        };
    };
    units: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitRow"][];
                };
            };
        };
    };
    history: {
        parameters: {
            query?: {
                hours?: number;
            };
            header?: never;
            path: {
                hazard: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
