"""Numeric/string parity with the legacy TypeScript backend (tests/fixtures/parity.json,
generated by tools/gen-parity.ts). Numbers within 1e-9, strings exact; simulationId and
alert ids are counters/timestamps, so they are compared by shape only.
"""

import json
import math
import re
from dataclasses import replace
from datetime import datetime
from pathlib import Path

import pytest

from climate.pdim import aqi, flood, geo, heat, risk, simulation
from climate.pdim.constants import DEFAULT_CITY, get_aqi_category
from climate.spatial.catalogue import legacy_catalogue, load_catalogue
from climate.spatial.units import AQI_POINTS, HEAT_CELLS

FIXTURE = json.loads((Path(__file__).parents[1] / "fixtures" / "parity.json").read_text(encoding="utf-8"))
SCENARIOS = {s["id"]: s for s in FIXTURE["scenarios"]}

SHAPE_ONLY = {"simulationId": re.compile(r"^sim-\d+-\d+$"), "id": re.compile(r"^alert-\d+-\d+$")}


def assert_same(actual, expected, path="$", shape_ids=False):
    if isinstance(expected, dict):
        assert isinstance(actual, dict), path
        assert actual.keys() == expected.keys(), f"{path}: {sorted(actual)} != {sorted(expected)}"
        for k, v in expected.items():
            if k in SHAPE_ONLY and (k == "simulationId" or shape_ids):
                assert SHAPE_ONLY[k].match(actual[k]), f"{path}.{k}: {actual[k]!r}"
            else:
                assert_same(actual[k], v, f"{path}.{k}", shape_ids)
    elif isinstance(expected, list):
        assert isinstance(actual, list | tuple), path
        assert len(actual) == len(expected), f"{path}: len {len(actual)} != {len(expected)}"
        for i, (a, e) in enumerate(zip(actual, expected, strict=True)):
            assert_same(a, e, f"{path}[{i}]", shape_ids)
    elif isinstance(expected, bool) or expected is None or isinstance(expected, str):
        assert actual == expected and type(actual) is type(expected), f"{path}: {actual!r} != {expected!r}"
    else:
        assert isinstance(actual, int | float) and not isinstance(actual, bool), f"{path}: {actual!r}"
        assert math.isclose(actual, expected, rel_tol=0, abs_tol=1e-9), f"{path}: {actual!r} != {expected!r}"


# ── pure grids ───────────────────────────────────────────────────────────────
PURE = {
    "floodRiskScore": risk.flood_risk_score,
    "floodRiskLevel": risk.flood_risk_level,
    "estimatedDepthM": risk.estimated_depth_m,
    "heatIndex": risk.heat_index,
    "effectiveTemp": risk.effective_temp,
    "aqiNowcastStep": risk.aqi_nowcast_step,
    "pm25ToAQI": aqi.pm25_to_aqi,
    "aqiLevel": risk.aqi_level,
    "aqiCategory": get_aqi_category,
    "generateFloodPolygon": geo.generate_flood_polygon,
}


def test_every_pure_group_is_covered():
    assert set(FIXTURE["pure"]) == set(PURE) | {"validateScenario"}


@pytest.mark.parametrize("name", sorted(PURE))
def test_pure(name):
    fn = PURE[name]
    for case in FIXTURE["pure"][name]:
        assert_same(fn(*case["args"]), case["out"], f"{name}{case['args']}")


def test_validate_scenario():
    for case in FIXTURE["pure"]["validateScenario"]:
        assert simulation.validate_scenario(case["scenario"]) == case["out"], case["scenario"]


# ── scenarios ────────────────────────────────────────────────────────────────
# S-002 changed the flood model (per-zone P(i); Ĩ = WorldCover builtUp replaces the soil-saturation
# proxy; city T̃/Ĩ/D̃ = zone means), the rule base (per unit, E(i) = builtUp) and the alerts (per-unit
# band rises), so flood / recommend / alerts are tested against hand-computed values in
# test_pdim_invariants.py, not here. The R_f formula itself keeps parity via the floodRiskScore grid.
# Heat and AQI formulas are unchanged: with the LEGACY catalogue (ρ = urbanDensity) and every unit
# on the city weather they reproduce the legacy payloads exactly.
def _inputs(s):
    now = datetime.fromisoformat(s["now"])
    weather = s["inputs"]["weather"]
    aq = s["inputs"]["airQuality"]

    def raw(lat, lng):
        current = aq.get(f"{lat!r},{lng!r}")
        return None if current is None else aqi.raw_from_open_meteo(current)

    city = raw(DEFAULT_CITY["lat"], DEFAULT_CITY["lng"])
    stations = [raw(p["lat"], p["lng"]) for p in AQI_POINTS]
    aq_out = aqi.compute_aqi(city, stations, weather["forecast"], now)
    return now, weather, aq_out


@pytest.fixture(params=sorted(SCENARIOS), ids=str)
def scenario(request):
    s = SCENARIOS[request.param]
    return s, *_inputs(s)


def heat_controller_shape(raw: dict) -> dict:
    """Legacy heatController's reshape of heat.service output (what /api/heat served)."""
    names = {c["id"]: c["name"] for c in HEAT_CELLS}  # S-002 §A.1 renames; parity.json keeps legacy names
    temps = [h["effectiveTemperature"] for h in raw["hotspots"]]
    return {
        "city": "hcmc",
        "timestamp": raw["timestamp"],
        "avgTemperature": raw["cityAvgTemp"],
        "maxTemperature": raw["cityMaxEffectiveTemp"],
        "heatIslandIntensity": raw["uhiEffect"],
        "avgEffectiveTemperature": math.floor(sum(temps) / len(temps) * 10 + 0.5) / 10,
        "hotspots": [
            {"id": h["id"], "name": names[h["id"]], "lat": h["lat"], "lng": h["lng"]}
            | {"temperature": h["effectiveTemperature"], "intensity": h["urbanDensity"]}
            for h in raw["hotspots"]
        ],
        "geojson": {
            "type": "FeatureCollection",
            "features": [
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [h["lng"], h["lat"]]},
                    "properties": {"temperature": h["effectiveTemperature"], "intensity": h["urbanDensity"]},
                }
                for h in raw["hotspots"]
            ],
        },
    }


def test_heat(scenario):
    s, now, weather, _ = scenario
    cur = weather["current"]
    legacy = legacy_catalogue()
    # The legacy model had no green layer (NaN); G₀ is an S-002 addition, so give it a value.
    cat = replace(legacy, heat_cells=tuple(replace(c, green=0.0) for c in legacy.heat_cells))
    got = heat.compute_heat({c["id"]: cur for c in HEAT_CELLS}, cur, now, cat)
    assert got.pop("baselines")["density"] == round(legacy.mean_built_up_heat, 3)  # S-002 addition
    assert_same(got, heat_controller_shape(s["outputs"]["heat"]), "heat")


def test_aqi(scenario):
    s, _, _, aq = scenario
    assert aq.pop("observedStations") == []  # S-002 addition (§D), empty without open-network readings
    assert_same(aq, s["outputs"]["aqi"], "aqi")


def test_legacy_simulations(scenario):
    """The S-001 what-if /v1/simulation still serves until T-104 switches it to run_counterfactual."""
    s, now, weather, aq = scenario
    fl = s["outputs"]["flood"]
    for i, sim in enumerate(s["outputs"]["simulations"]):
        sc = sim["request"]["scenario"]
        assert simulation.validate_scenario(sc) is None
        got = simulation.run_simulation(
            sc, weather, fl, aq, now, simulation_id=f"sim-{risk.epoch_ms(now)}-{i + 1}"
        )
        assert_same(got, sim["result"], f"simulations[{i}]")
        assert got["simulationId"] == sim["result"]["simulationId"]  # counter = call order in a fresh process


def test_counterfactual_keeps_city_aqi_and_green_temp_parity(scenario):
    """§G kept two city-level formulas: ΔAQI (ṽ = 1, γ_p washout on the added rain) and, when the
    density slider is untouched, ΔT = −α·ΔG. Everything else is per unit (test_pdim_invariants)."""
    s, now, weather, aq = scenario
    cur = weather["current"]
    cat = load_catalogue()
    zones = {z.id: cur["rainfall"] for z in cat.flood_zones}
    points = {u: {"rainfall": cur["rainfall"]} for u in [*(p.id for p in cat.aqi_points), "city"]}
    snaps = {
        "flood": {
            "inputs": {"rainfall": zones, "cityRainfall": cur["rainfall"]},
            "result": flood.compute_flood(zones, cur["rainfall"], cat),
        },
        "heat": {
            "inputs": {},
            "result": heat.compute_heat({c.id: cur for c in cat.heat_cells}, cur, now, cat),
        },
        "aqi": {"inputs": {"pointWeather": points}, "result": aq},
    }
    for sim in s["outputs"]["simulations"]:
        sc = sim["request"]["scenario"]
        got = simulation.run_counterfactual(sc, snaps, now, cat)["results"]
        assert_same(got["aqiDelta"], sim["result"]["results"]["aqiDelta"], "aqiDelta")
        if sc.get("urbanDensity") is None:
            assert_same(got["tempDelta"], sim["result"]["results"]["tempDelta"], "tempDelta")


# ── JS parity helpers ────────────────────────────────────────────────────────
def test_js_helpers():
    assert [risk.js_round(x) for x in (2.5, -2.5, 0.5, -0.5, 1.4999, 3.0)] == [3, -2, 1, 0, 1, 3]
    assert risk.to_fixed(0.125, 2) == "0.13"  # Python's format gives "0.12"
    assert risk.to_fixed(2.5, 0) == "3" and risk.to_fixed(1.005, 2) == "1.00"  # 1.005 is below the tie
    assert risk.to_fixed(53.3, 0) == "53" and risk.to_fixed(0, 1) == "0.0"
    now = datetime.fromisoformat("2026-09-23T22:30:05.123456+00:00")
    assert risk.js_iso(now) == "2026-09-23T22:30:05.123Z"
    assert risk.epoch_ms(datetime.fromisoformat("2026-02-10T03:00:00Z")) == 1770692400000
