"""Numeric/string parity with the legacy TypeScript backend (tests/fixtures/parity.json,
generated by tools/gen-parity.ts). Numbers within 1e-9, strings exact; simulationId and
alert ids are counters/timestamps, so they are compared by shape only.
"""

import json
import math
import re
from datetime import datetime
from pathlib import Path

import pytest

from climate.pdim import aqi, flood, geo, heat, risk, rules, simulation
from climate.pdim.constants import DEFAULT_CITY, get_aqi_category
from climate.spatial.units import AQI_POINTS, HEAT_CELLS

FIXTURE = json.loads((Path(__file__).parents[1] / "fixtures" / "parity.json").read_text(encoding="utf-8"))
SCENARIOS = {s["id"]: s for s in FIXTURE["scenarios"]}

SHAPE_ONLY = {"simulationId": re.compile(r"^sim-\d+-\d+$"), "id": re.compile(r"^alert-\d+-\d+$")}


def assert_same(actual, expected, path="$", shape_ids=False):
    if isinstance(expected, dict):
        assert isinstance(actual, dict), path
        assert actual.keys() == expected.keys(), f"{path}: {sorted(actual)} != {sorted(expected)}"
        for k, v in expected.items():
            if k in SHAPE_ONLY and (k == "simulationId" or shape_ids):
                assert SHAPE_ONLY[k].match(actual[k]), f"{path}.{k}: {actual[k]!r}"
            else:
                assert_same(actual[k], v, f"{path}.{k}", shape_ids)
    elif isinstance(expected, list):
        assert isinstance(actual, list | tuple), path
        assert len(actual) == len(expected), f"{path}: len {len(actual)} != {len(expected)}"
        for i, (a, e) in enumerate(zip(actual, expected, strict=True)):
            assert_same(a, e, f"{path}[{i}]", shape_ids)
    elif isinstance(expected, bool) or expected is None or isinstance(expected, str):
        assert actual == expected and type(actual) is type(expected), f"{path}: {actual!r} != {expected!r}"
    else:
        assert isinstance(actual, int | float) and not isinstance(actual, bool), f"{path}: {actual!r}"
        assert math.isclose(actual, expected, rel_tol=0, abs_tol=1e-9), f"{path}: {actual!r} != {expected!r}"


# ── pure grids ───────────────────────────────────────────────────────────────
PURE = {
    "floodRiskScore": risk.flood_risk_score,
    "floodRiskLevel": risk.flood_risk_level,
    "estimatedDepthM": risk.estimated_depth_m,
    "heatIndex": risk.heat_index,
    "effectiveTemp": risk.effective_temp,
    "aqiNowcastStep": risk.aqi_nowcast_step,
    "pm25ToAQI": aqi.pm25_to_aqi,
    "aqiLevel": risk.aqi_level,
    "aqiCategory": get_aqi_category,
    "generateFloodPolygon": geo.generate_flood_polygon,
}


def test_every_pure_group_is_covered():
    assert set(FIXTURE["pure"]) == set(PURE) | {"validateScenario"}


@pytest.mark.parametrize("name", sorted(PURE))
def test_pure(name):
    fn = PURE[name]
    for case in FIXTURE["pure"][name]:
        assert_same(fn(*case["args"]), case["out"], f"{name}{case['args']}")


def test_validate_scenario():
    for case in FIXTURE["pure"]["validateScenario"]:
        assert simulation.validate_scenario(case["scenario"]) == case["out"], case["scenario"]


# ── scenarios ────────────────────────────────────────────────────────────────
def _inputs(s):
    now = datetime.fromisoformat(s["now"])
    weather = s["inputs"]["weather"]
    aq = s["inputs"]["airQuality"]

    def raw(lat, lng):
        current = aq.get(f"{lat!r},{lng!r}")
        return None if current is None else aqi.raw_from_open_meteo(current)

    city = raw(DEFAULT_CITY["lat"], DEFAULT_CITY["lng"])
    stations = [raw(p["lat"], p["lng"]) for p in AQI_POINTS]
    fl = flood.compute_flood(weather["current"]["rainfall"], s["month"])
    aq_out = aqi.compute_aqi(city, stations, weather["forecast"], now)
    return now, weather, fl, aq_out


@pytest.fixture(params=sorted(SCENARIOS), ids=str)
def scenario(request):
    s = SCENARIOS[request.param]
    return s, *_inputs(s)


def test_flood(scenario):
    s, _, _, fl, _ = scenario
    assert_same(fl, s["outputs"]["flood"], "flood")


def test_heat(scenario):
    s, now, weather, _, _ = scenario
    want = s["outputs"]["heat"]
    # S-002 §A.1 renamed 12 cells; parity.json keeps the legacy names, so expect units.py's by id.
    names = {c["id"]: c["name"] for c in HEAT_CELLS}
    want = want | {"hotspots": [h | {"name": names[h["id"]]} for h in want["hotspots"]]}
    assert_same(heat.compute_heat(weather["current"], now), want, "heat")


def test_aqi(scenario):
    s, _, _, _, aq = scenario
    assert_same(aq, s["outputs"]["aqi"], "aqi")


def test_recommend(scenario):
    s, now, weather, fl, aq = scenario
    assert_same(rules.recommendations(weather, fl, aq, now), s["outputs"]["recommend"], "recommend")


def test_alerts_first_call(scenario):
    s, now, weather, fl, aq = scenario
    alerts = rules.new_alerts(weather, fl, aq, now, active=[])
    got = {
        "alerts": sorted(alerts, key=lambda a: a["createdAt"], reverse=True),
        "unreadCount": sum(not a["isRead"] for a in alerts),
        "totalCount": len(alerts),
    }
    assert_same(got, s["outputs"]["alertsFirstCall"], "alerts", shape_ids=True)


def test_simulations(scenario):
    s, now, weather, fl, aq = scenario
    for i, sim in enumerate(s["outputs"]["simulations"]):
        sc = sim["request"]["scenario"]
        assert simulation.validate_scenario(sc) is None
        got = simulation.run_simulation(
            sc, weather, fl, aq, now, simulation_id=f"sim-{risk.epoch_ms(now)}-{i + 1}"
        )
        assert_same(got, sim["result"], f"simulations[{i}]")
        assert got["simulationId"] == sim["result"]["simulationId"]  # counter = call order in a fresh process


# ── JS parity helpers ────────────────────────────────────────────────────────
def test_js_helpers():
    assert [risk.js_round(x) for x in (2.5, -2.5, 0.5, -0.5, 1.4999, 3.0)] == [3, -2, 1, 0, 1, 3]
    assert risk.to_fixed(0.125, 2) == "0.13"  # Python's format gives "0.12"
    assert risk.to_fixed(2.5, 0) == "3" and risk.to_fixed(1.005, 2) == "1.00"  # 1.005 is below the tie
    assert risk.to_fixed(53.3, 0) == "53" and risk.to_fixed(0, 1) == "0.0"
    now = datetime.fromisoformat("2026-09-23T22:30:05.123456+00:00")
    assert risk.js_iso(now) == "2026-09-23T22:30:05.123Z"
    assert risk.epoch_ms(datetime.fromisoformat("2026-02-10T03:00:00Z")) == 1770692400000
